# Generated by Django 4.2.10 on 2026-04-05 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.lga')),
            ],
            options={
                'ordering': ['lga', 'name'],
                'unique_together': {('name', 'lga')},
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='locations.lga')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='locations.ward')),
            ],
            options={
                'ordering': ['unit_id'],
                'indexes': [models.Index(fields=['lga'], name='locations_p_lga_id_220763_idx'), models.Index(fields=['ward'], name='locations_p_ward_id_404a98_idx'), models.Index(fields=['unit_id'], name='locations_p_unit_id_6e1668_idx')],
            },
        ),
    ]
