# Generated by Django 4.2.10 on 2026-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_add_plaintext_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='plaintext_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='unit_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
