# Generated by Django 4.2.10 on 2026-04-13 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('election_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-election_date'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(blank=True, default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectionParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_parties', to='elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_parties', to='elections.party')),
            ],
            options={
                'ordering': ['election', 'party'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='elections_e_status_e3ccd0_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_date'], name='elections_e_electio_b68a29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electionparty',
            unique_together={('election', 'party')},
        ),
    ]
