"""
Serializers for the locations app - converts LGA, Ward, PollingUnit models to/from JSON
"""
from rest_framework import serializers
from .models import LGA, Ward, PollingUnit


class LGASerializer(serializers.ModelSerializer):
    """Serializer for LGA model"""
    ward_count = serializers.SerializerMethodField()
    
    class Meta:
        model = LGA
        fields = ['id', 'name', 'acronym', 'ward_count', 'created_at']
        read_only_fields = ['id', 'created_at']
    
    def get_ward_count(self, obj):
        """Get the number of wards in this LGA"""
        return obj.wards.count()


class WardSerializer(serializers.ModelSerializer):
    """Serializer for Ward model"""
    lga_name = serializers.CharField(source='lga.name', read_only=True)
    polling_unit_count = serializers.SerializerMethodField()
    
    class Meta:
        model = Ward
        fields = ['id', 'name', 'lga', 'lga_name', 'polling_unit_count', 'created_at']
        read_only_fields = ['id', 'created_at']
    
    def get_polling_unit_count(self, obj):
        """Get the number of polling units in this ward"""
        return obj.polling_units.count()


class PollingUnitSerializer(serializers.ModelSerializer):
    """Serializer for PollingUnit model"""
    ward_name = serializers.CharField(source='ward.name', read_only=True)
    lga_name = serializers.CharField(source='lga.name', read_only=True)
    
    class Meta:
        model = PollingUnit
        fields = [
            'id', 'unit_id', 'name', 'ward', 'ward_name',
            'lga', 'lga_name', 'is_active', 'created_at'
        ]
        read_only_fields = ['id', 'unit_id', 'created_at']
        # Password should never be included in API response
        extra_kwargs = {
            'password': {'write_only': True}  # Only accept password when writing, never return it
        }


class PollingUnitDetailSerializer(PollingUnitSerializer):
    """Extended PollingUnit serializer with password for admin"""
    
    class Meta(PollingUnitSerializer.Meta):
        fields = PollingUnitSerializer.Meta.fields + ['updated_at', 'password']
        read_only_fields = ['id', 'unit_id', 'created_at', 'updated_at']


class PollingUnitListSerializer(serializers.ModelSerializer):
    """Serializer for polling unit lists with ward and lga names (NO passwords)"""
    ward_name = serializers.CharField(source='ward.name', read_only=True)
    lga_name = serializers.CharField(source='lga.name', read_only=True)
    
    class Meta:
        model = PollingUnit
        fields = ['id', 'unit_id', 'name', 'ward', 'ward_name', 'lga', 'lga_name', 'is_active', 'created_at']
        read_only_fields = ['id', 'unit_id', 'created_at']


class PollingUnitCreateSerializer(serializers.ModelSerializer):
    """
    Serializer for creating polling units - accepts only name, ward, lga.
    Password is auto-generated by the view.
    """
    class Meta:
        model = PollingUnit
        fields = ['name', 'ward', 'lga']


class PollingUnitCreateResponseSerializer(serializers.ModelSerializer):
    """
    Serializer for creation response - includes plain-text password (ephemeral).
    This password exists only in the API response, never in the database.
    """
    ward_name = serializers.CharField(source='ward.name', read_only=True)
    lga_name = serializers.CharField(source='lga.name', read_only=True)
    temporary_password = serializers.SerializerMethodField()
    
    class Meta:
        model = PollingUnit
        fields = ['id', 'unit_id', 'name', 'ward', 'ward_name', 'lga', 'lga_name', 'temporary_password', 'created_at']
        read_only_fields = ['id', 'unit_id', 'name', 'ward', 'lga', 'created_at']
    
    def get_temporary_password(self, obj):
        """Return the temporary password from request context"""
        return self.context.get('temporary_password', '')


class PasswordResetResponseSerializer(serializers.Serializer):
    """Response for password reset - includes temporary password (ephemeral)"""
    status = serializers.CharField(default='success')
    message = serializers.CharField()
    pu_code = serializers.CharField()  # unit_id
    pu_name = serializers.CharField()
    temporary_password = serializers.CharField()
    warning = serializers.CharField(default='This password will not be shown again. Please share it with the agent immediately.')
